services:
  database:
    image: ghcr.io/singlestore-labs/singlestoredb-dev:latest
    platform: linux/amd64
    command: []
    environment:
      MYSQL_DATABASE: !reset null
      MYSQL_USER: !reset null
      MYSQL_PASSWORD: !reset null
      MYSQL_ROOT_PASSWORD: !reset null
      ROOT_PASSWORD: repro
    healthcheck: !override
      test: ["CMD-SHELL", "singlestore -uroot -prepro -e 'SELECT 1'"]
      interval: 2s
      timeout: 3s
      retries: 45
      start_period: 10s

  php:
    environment:
      PHP_VERSION: ${PHP_VERSION:-8.6.0alpha3}
      DB_HOST: ${DB_HOST:-database}
      DB_PORT: ${DB_PORT:-3306}
      DB_NAME: ${DB_NAME:-}
      DB_USER: ${DB_USER:-root}
      DB_PASSWORD: ${DB_PASSWORD:-repro}
      DB_SERVER: singlestore
    command: ["php", "/app/repro-mysql-protocol.php"]
